
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/empsandun?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:
    show-sql: true

